name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build server
      run: |
        cd server
        cargo build --verbose
    - name: Run server in background
      run: |
        cd server
        cargo run > ~/server_output 2>&1 &
    - name: Run swift test
      run: |
        cd client
        xcodebuild test -project client.xcodeproj -scheme clientTests -destination 'platform=iOS Simulator,name=iPhone 8,OS=14.4'
    - name: Run swift test
      if: ${{ always() }}
      run: |
        cat ~/server_output
